#该工作流会构建docker容器，当有push到“main”分支时，发布并部署到腾讯Kubernetes Engine(TKE)。
#
#配置此工作流：
#
#1.确保您的存储库包含用于您的腾讯Kubernetes引擎集群的必要配置，
#包括部署.yml、kustomization.yml、service。yml等
#
#2.在工作区中设置秘密：
#-TENCENT_CLOUD_SECRET_ID，带腾讯云密码
#-TENCENT_CLOUD_SECRET_KEY带腾讯云密钥
#-腾讯云账号为TENCENT_CLOUD_ACCOUNT_ID
#-TKE_REGISTRY_PASSWORD，带TKE注册表密码
#
#3.更改TKE_IMAGE_URL、TKE_REGION、TKE_CLUSTER_ID和DEPLOYMENT_NAME环境变量的值(如下所示)。

姓名:腾讯Kubernetes引擎

在……之上:
推:
分支机构:[ "主要" ]

#此工作流中所有作业和步骤可用的环境变量
env:
TKE_IMAGE_URL:ccr.ccs.tencentyun.com/demo/myWebApp
TKE_REGION:ap-广州
TKE_CLUSTER_ID:cls-mywebapp
deployment_NAME:tke-test

权限:
内容:读

工作:
设置-构建-发布-部署:
姓名:安装、生成、发布和部署
run-on:ubuntu-最新
环境:生产
步骤:

-姓名:结帐
uses:操作/结帐@v4

    #Build
-姓名:构建Docker映像
跑:|
Docker构建-t${TKE_IMAGE_URL}：${GITHUB_SHA}。

-姓名:登录TKE注册表
跑:|
Docker登录-u${{secrets.TENCENT_CLOUD_ACCOUNT_ID}}-p'${{secrets.TKE_REGISTRY_PASSWORD}}'${TKE_IMAGE_URL}

    #将Docker映像推送到TKE注册表
-姓名:出版
跑:|
Docker推送${TKE_IMAGE_URL}：${GITHUB_SHA}

-姓名:设置Kustomize
跑:|
curl-o kustomize--location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
chmod u+x./k自定义

-姓名:设置连接TKE群集的~/.kube/config
uses:腾讯云/tke-cluster-credential-action@v1
和……一起:
secret_id:${{secrets.TENCENT_CLOUD_SECRET_ID}}
        secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        tke_region: ${{ env.TKE_REGION }}
        cluster_id: ${{ env.TKE_CLUSTER_ID }}

    - name: Switch to TKE context
      run: |
        kubectl config use-context ${TKE_CLUSTER_ID}-context-default

    # Deploy the Docker image to the TKE cluster
    - name: Deploy
      run: |
        ./kustomize edit set image ${TKE_IMAGE_URL}:${GITHUB_SHA}
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/${DEPLOYMENT_NAME}
        kubectl get services -o wide
